language: python
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - build-essential
    - automake
    - pkg-config
    - libtool
    - libffi-dev
    - libgmp-dev
matrix:
  include:
  # lint
  - python: "3.5"
    env: TOX_ENV=flake8
  # mypy
  - python: "3.5"
    env: TOX_ENV=mypy
  # core
  - python: "3.4"
    env: TOX_ENV=py34-core
  - python: "3.5"
    env: TOX_ENV=py35-core
  - python: "3.6"
    env: TOX_ENV=py36-core
  # backends
  - python: "3.4"
    env: TOX_ENV=py34-backends
  - python: "3.5"
    env: TOX_ENV=py35-backends
  - python: "3.6"
    env: TOX_ENV=py36-backends
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
