language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - build-essential
    - automake
    - pkg-config
    - libtool
    - libffi-dev
    - libgmp-dev
env:
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=flake8
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
